---

- hosts: all

  tasks:
  # - name: Install Git
  #   ansible.builtin.package:
  #     name: git
  #     state: latest
  # - name: Install vim
  #   ansible.builtin.package:
  #     name: vim
  #     state: latest

  # # OpenMP
  # - name: Copy OpenMP File to RPI
  #   ansible.builtin.copy:
  #     src: ../../test_code/openmp_helloworld.cpp
  #     dest: /home/sam/openmp_helloworld.cpp
  #     owner: sam
  #     group: sam
  #     mode: '0644'
  # - name: Test OpenMP functionality
  #   ansible.builtin.shell: |
  #     g++ openmp_helloworld.cpp -o test.o -fopenmp
  #     ./test.o
  #   register: OpenMPresults
  # - name: Output OpenMP
  #   debug: 
  #     var: OpenMPresults

# TODO MAYBE remove dup entries in NODE0

  # # OpenMPI
  # - name: Install OpenMPI
  #   ansible.builtin.package:
  #     name:
        # - openmpi-common
        # - openmpi-bin
        # - openmpi-doc
        # - libopenmpi-dev
  #     state: latest
  # - name: Copy OpenMPI File to RPI
  #   ansible.builtin.copy:
  #     src: ../../test_code/openmpi_helloworld.cpp
  #     dest: /home/sam/openmpi_helloworld.cpp
  #     owner: sam
  #     group: sam
  #     mode: '0644'
  # - name: Test OpenMPI functionality
  #   ansible.builtin.shell: |
  #     mpicc openmpi_helloworld.cpp -o openmpi
  #     mpiexec -n 4 ./openmpi
  #   register: OpenMPIresults
  # - name: Output OpenMPI
  #   debug: 
  #     var: OpenMPIresults

  # NFS!!!
  # https://bluexp.netapp.com/blog/azure-anf-blg-linux-nfs-server-how-to-set-up-server-and-client
  
  # NFS Server Set-Up on Master
  # - name: Install NFS-Kernel-Server
  #   ansible.builtin.package:
  #     name: nfs-kernel-server
  #     state: latest
  #   when: inventory_hostname in groups['master']
  # - name: NFS Share set up
  #   ansible.builtin.shell: |
  #     sudo mkdir /mnt/shareddrive2
  #     sudo chown nobody:nogroup /mnt/shareddrive2
  #     sudo chmod 777 /mnt/shareddrive2
  #   when: inventory_hostname in groups['master']
  # - name: Update /etc/exports file manually (Check LINK on formatting file)
  # - name: NFS Share Restart
  #   ansible.builtin.shell: |
  #     sudo exportfs -a
  #     sudo systemctl restart nfs-kernel-server
  #   when: inventory_hostname in groups['master']

  # - name: Install NFS-Common
  #   ansible.builtin.package:
  #     name: nfs-common
  #     state: latest
  #   when: inventory_hostname in groups['worker']

  # [TODO]
  # - name: Mount NFS File Share 
  #   ansible.builtin.shell: |
  #     sudo mkdir /var/shareddrive
  #   become: true
  #   when: inventory_hostname in groups['worker']

  # [TODO] Ansible
  # Update /etc/fstab with {IP of NFS server}:{folder path on server} /var/locally-mounted nfs defaults 0 0 (tab separating)
  
  # - name: Restart NFS File Share
  #   ansible.builtin.shell: |
  #     systemctl daemon-reload
  #     mount /var/shareddrive
  #     mount 10.0.50.130:/mnt/shareddrive/
  #   when: inventory_hostname in groups['worker']

#########
# MUNGE #
#########

  # - name: Install Munge on Master Node
  #   ansible.builtin.shell: |
  #     apt install munge libmunge2 libmunge-dev -y
  #     munge -n | unmunge | grep STATUS
  #   when: inventory_hostname in groups['master']
  #   register: MungeMasterNodeOutput
  # - name: Output MungeMasterNodeOutput
  #   debug: 
  #     var: MungeMasterNodeOutput

  # - name: Setup Munge on Master Node
  #   ansible.builtin.shell: |
  #     sudo chown -R munge: /etc/munge/ /var/log/munge/ /var/lib/munge/ /run/munge/
  #     sudo chmod 0700 /etc/munge/ /var/log/munge/ /var/lib/munge/
  #     sudo chmod 0755 /run/munge/
  #     sudo chmod 0700 /etc/munge/munge.key
  #     sudo chown -R munge: /etc/munge/munge.key
  #     systemctl enable munge
  #     systemctl restart munge
  #   when: inventory_hostname in groups['master']

  # - name: Check Munge Status
  #   ansible.builtin.shell: |
  #     systemctl status munge
  #   when: inventory_hostname in groups['master']
  #   register: MungeStatus
  # - name: Output MungeStatus
  #   debug: 
  #     var: MungeStatus

  # - name: Install Munge on Worker Nodes
  #   ansible.builtin.shell: |
  #     apt install munge libmunge2 libmunge-dev -y
  #     munge -n | unmunge | grep STATUS
  #   when: inventory_hostname in groups['worker']
  #   register: MungeWorkerNodeOutput
  # - name: Output MungeWorkerNodeOutput
  #   debug: 
  #     var: MungeWorkerNodeOutput

# Worker Nodes need the same key as the Master node. So I copied it over manually for security.
  # - name: Setup Munge on Worker Node
  #   ansible.builtin.shell: |
  #     sudo chown -R munge: /etc/munge/ /var/log/munge/ /var/lib/munge/ /run/munge/
  #     sudo chmod 0700 /etc/munge/ /var/log/munge/ /var/lib/munge/
  #     sudo chmod 0755 /run/munge/
  #     sudo chmod 0700 /etc/munge/munge.key
  #     sudo chown -R munge: /etc/munge/munge.key
  #     systemctl enable munge
  #     systemctl restart munge
  #   when: inventory_hostname in groups['worker']

  # - name: Check Munge Worker Status
  #   ansible.builtin.shell: |
  #     systemctl status munge
  #   when: inventory_hostname in groups['worker']
  #   register: MungeStatusWorker
  # - name: Output MungeStatusWorker
  #   debug: 
  #     var: MungeStatusWorker

#########
# SLURM #
#########

  # - name: Install Slurm on All Nodes
  #   ansible.builtin.shell: |
  #     sudo apt-get update
  #     sudo apt-get install slurm-wlm -y
  # - name: Install Slurm on All Nodes
  #   ansible.builtin.shell: |
  #     sudo apt-get update
  #     sudo apt-get install slurm-wlm -y
  # - name: Copy file with owner and permissions
  #   ansible.builtin.copy:
  #     src: ../../slurm.conf
  #     dest: /etc/slurm/slurm.conf
  # - name: Test
  #   ansible.builtin.command:


